models/Cars.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cars".
 *
 * @property int $id
 * @property string $name
 * @property string $number
 * @property string $tracker
 * @property string $mark
 * @property int $voditel_id
 *
 * @property User $voditel
 */
class Cars extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cars';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'number', 'voditel_id'], 'required'],
            [['voditel_id'], 'integer'],
            [['name', 'number', 'mark', 'status', 'tracker'], 'string', 'max' => 255],
            [['voditel_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['voditel_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'number' => 'Номер',
            'mark' => 'Марка',
            'voditel_id' => 'ID Водителя',
            'status' => 'Статус',
            'tracker' => 'Трэкер',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVoditel()
    {
        return $this->hasOne(User::className(), ['id' => 'voditel_id']);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->status = "Свободен"; 
            }
            return true;
        }
        return false;
    }

    public function getVoditel_idText()
    {
        return $this->voditel->name;
    }
    
    public function setVoditel_idText($value)
    {
        $this->voditel_id = $this->voditel_id;
    }

}

controllers/CarsController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use app\models\Cars;
use app\models\CarsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

/**
 * CarsController implements the CRUD actions for Cars model.
 */
class CarsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cars models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new CarsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Cars model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Автомобиль #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Готово',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Cars model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Cars();
        $data_query = (new \yii\db\Query())
        ->select(['id','name'])
        ->from('user')
        ->where(['role' => 'VODITEL'])
        ->all();

        $data = ArrayHelper::map($data_query, 'id', 'name');        

         

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Создание автомобиля",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                        'data' => $data,
                        'action' => 'cars/create',
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Создание автомобиля",
                    'content'=>'<span class="text-success">Добавлено успешно</span>',
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Создание автомобиля",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                        'data' => $data,
                        'action' => 'cars/create',
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Создать',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'data' => $data,
                    'action' => 'cars/create',
                ]);
            }
        }
       
    }

    /**
     * Updates an existing Cars model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $data_query = (new \yii\db\Query())
        ->select(['id','name'])
        ->from('user')
        ->where(['role' => 'VODITEL'])
        ->all();
        $data = ArrayHelper::map($data_query, 'id', 'name');       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить автомобиль #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                        'data' => $data,
                        'action' => 'cars/create',
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Автомобиль #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $model,
                        'action' => 'cars/create',
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
            }else{
                 return [
                    'title'=> "Изменить автомобиль #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                        'data' => $data,
                        'action' => 'create',
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'data' => $data,
                    'action' => 'create',
                ]);
            }
        }
    }

    /**
     * Delete an existing Cars model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing Cars model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }
    public function actionSessionForm()
    {
        Yii::$app->session->set('cars-form-session', ArrayHelper::getValue($_POST, 'Cars'));
    }
    public function actionCreateDriver()
    {

views/cars/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use app\models\User;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'number',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'mark',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'voditel_id',
        'value' => function ($model) {
            return $model->voditel_id . " (" . $model->voditel_idText . ")" ;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'tracker',
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'template' => Yii::$app->user->identity->role != User::ROLE_VODITEL ? '{update}{delete}' : '{update}',
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Изменить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                ])."&nbsp;";
            },
        ],
    ],

];   

views/cars/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Cars */
/* @var $form yii\widgets\ActiveForm */
/* @var $action string */
?>

<div class="cars-form">

    <?php $form = ActiveForm::begin(['id' => 'frm', 'action' => ["{$action}"]]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'number')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($model, 'mark')->textInput(['maxlength' => true]) ?>

    <div class="row" style="display: flex; align-items: center;">
        <div class="col-md-10" style="padding:0 6px ;">
            <?= $form->field($model, 'voditel_id')->widget(Select2::class, [
                'data' => $data,
                'options' => ['multiple' => false],
            ]) ?>
        </div>
        <div class="col-md-2" style="padding: 0">
            <?= Html::a("<i class='fa fa-plus'></i>", ['cars/create-driver'], [
                'class' => 'btn btn-default btn-block',
                'style' => 'margin-top: 10px;',
                'role' => 'modal-remote',
                'onclick' => '
                        
                                    var $form = $("#frm");
                                    $.ajax({
                                      type: "POST",
                                      url: "cars/session-form",
                                      data: $form.serialize(),
                                    }).done(function() {
                                      console.log(\'success\');
                                    }).fail(function() {
                                      console.log(\'fail\');
                                    });
                        ',
            ]) ?>

        </div>
    </div>

    <?= $form->field($model, 'tracker')->textInput(['maxlength' => true]) ?>    
    
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/cars/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Cars */

?>
<div class="cars-create">
    <?= $this->render('_form', [
        'model' => $model,
        'data' => $data,
        'action' => $action
    ]) ?>
</div>

views/cars/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CarsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Автомобили';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);
if(Yii::$app->user->identity->role != \app\models\User::ROLE_VODITEL)
{
    $panelBeforeTemplate = Html::a('Добавить <i class="fa fa-plus"></i>', ['create'], ['role'=>'modal-remote','title'=> 'Добавить автомобиль','class'=>'btn btn-success']).
        '&nbsp;'.
        Html::a('<i class="fa fa-repeat"></i>', [''], ['data-pjax'=>1, 'class'=>'btn btn-white', 'title'=>'Обновить']);
        $panelAfterTemplate = Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
        ["bulk-delete"] ,
        [
        "class"=>"btn btn-danger btn-xs",
        'role'=>'modal-remote-bulk',
        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
        'data-request-method'=>'post',
        'data-confirm-title'=>'Вы уверены?',
        'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
        ]);
} else {
    $panelBeforeTemplate = Html::a('<i class="fa fa-repeat"></i>', [''], ['data-pjax'=>1, 'class'=>'btn btn-white', 'title'=>'Обновить']);
    $panelAfterTemplate = "";
}
?>

<div class="panel panel-inverse cars-index">
    <div class="panel-heading">
<!--        <div class="panel-heading-btn">-->
<!--        </div>-->
        <h4 class="panel-title">Автомобили</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' => $panelBeforeTemplate,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>BulkButtonWidget::widget([
            'buttons'=> $panelAfterTemplate,
            ]).
            '<div class="clearfix"></div>',
            ]
            ])?>
        </div>
    </div>
</div>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/cars/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cars */
?>
<div class="cars-update">

    <?= $this->render('_form', [
        'model' => $model,
        'data' => $data,
        'action' => $action
    ]) ?>

</div>

views/cars/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cars */
?>

<div class="cars-view">

<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Информация</h4>
    </div>
    <div class="panel-body">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'name',
                'number',
                'mark',
                'voditel_id',
                'tracker'
            ],
        ]) ?>
    </div>
</div>

</div>